### ISSUE TITLE
Please fix or remove outdated code

### ISSUE THREAD

**Issue by hf-kklein** [MicrosoftDocs/azure-docs.de-de#120]
In May 2018 [you announced](https://github.com/Azure/app-service-announcements/issues/112) breaking changes in Azure Functions Runtime 2.0. This introduction still uses `import com.microsoft.azure.serverless.functions.annotation.*;` although this doesn't work anymore after the breaking changes.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5e85de04-2f8b-68ea-eeb9-dcc65f216332
* Version Independent ID: db26953c-f234-3828-4c38-493ad410e25a
* Content: [Java-Entwicklerreferenz zu Azure Functions](https://docs.microsoft.com/de-de/azure/azure-functions/functions-reference-java)
* Content Source: [articles/azure-functions/functions-reference-java.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/azure-functions/functions-reference-java.md)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #12726](https://github.com/MicrosoftDocs/azure-docs/issues/12726) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @hf-kklein , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/12726. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
