### ISSUE TITLE
fix dead links in section "Tabelle"

### ISSUE THREAD

**Issue by hf-kklein** [MicrosoftDocs/azure-docs.de-de#121]
The links in section "Tabelle" are mostly dead. E.g. https://github.com/Azure-Samples/storage-table-java-getting-started/blob/master/src/TableBasics.java

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6783e136-eeb6-054d-c257-ee3e7135caae
* Version Independent ID: 86cb3b76-050d-c9a3-0402-c2af496e7364
* Content: [Azure Storage-Beispiele mit Java](https://docs.microsoft.com/de-de/azure/storage/common/storage-samples-java)
* Content Source: [articles/storage/common/storage-samples-java.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/storage/common/storage-samples-java.md)
* Service: **storage**
* GitHub Login: @seguler
* Microsoft Alias: **seguler**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #12799](https://github.com/MicrosoftDocs/azure-docs/issues/12799) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @hf-kklein 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/12799. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
