### ISSUE TITLE
No bgp enabled on vpn gateway

### ISSUE THREAD

**Issue by nnamedieh** [MicrosoftDocs/azure-docs.de-de#126]
Hi all, thanks for your well written document! Going through this step by step instructions, I wondered why you enable bgp on the Azure service "Connection" but do not enable it on the vpn gateway. I'm a bit confused about this fact, because actually I don't know when I have to enable bgp on the vpn gateway and when I have to enable it on the "Connection". Maybe you can help me to figure it out?

Thank you!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 27b300f3-7b57-0772-9a36-6448a56b3d23
* Version Independent ID: 959e9abd-3033-df6c-cb30-8277b0acbf0d
* Content: [Konfigurieren von Aktiv/Aktiv-S2S-VPN-Verbindungen für VPN Gateways: Azure Resource Manager: PowerShell](https://docs.microsoft.com/de-de/azure/vpn-gateway/vpn-gateway-activeactive-rm-powershell)
* Content Source: [articles/vpn-gateway/vpn-gateway-activeactive-rm-powershell.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/vpn-gateway/vpn-gateway-activeactive-rm-powershell.md)
* Service: **vpn-gateway**
* GitHub Login: @yushwang
* Microsoft Alias: **yushwang, cherylmc**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13762](https://github.com/MicrosoftDocs/azure-docs/issues/13762) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @nnamedieh, 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/13762. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
