### ISSUE TITLE
You only need the first certificate from the output window.

### ISSUE THREAD

**Issue by Bnjmn83** [MicrosoftDocs/azure-docs.de-de#129]
Please fix the following section :

"... Copy to clipboard the output starting from -----BEGIN CERTIFICATE----- and ending at -----END CERTIFICATE-----, making sure to include both of these lines as well."

and add:

"You only need the first certificate from the output window."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6d13df1d-e132-c9b6-1efa-6d30550d72f7
* Version Independent ID: 7f720685-f1ee-baa8-4152-fc1104019e8e
* Content: [Bereitstellen eines simulierten X.509-Geräts für Azure IoT Hub mithilfe von Python](https://docs.microsoft.com/de-de/azure/iot-dps/quick-create-simulated-device-x509-python)
* Content Source: [articles/iot-dps/quick-create-simulated-device-x509-python.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-dps/quick-create-simulated-device-x509-python.md)
* Service: **iot-dps**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14487](https://github.com/MicrosoftDocs/azure-docs/issues/14487) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @Bnjmn83 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/14487.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
