### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by ithahn** [MicrosoftDocs/azure-docs.de-de#140]
Hi, can you please update this document for Windows Server 2016/2019 and of course it would be great if you mention data disks as well. Only Startup volume is not fully statisfying.

Thanks

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 246df0be-86c4-083f-5896-d9ed79a94b88
* Version Independent ID: cba0daf5-b5f3-e1ba-2d79-56ef94f927cb
* Content: [Azure Disk Encryption für virtuelle Windows- und Linux-IaaS-Computer](https://docs.microsoft.com/de-de/azure/security/azure-security-disk-encryption-appendix)
* Content Source: [articles/security/azure-security-disk-encryption-appendix.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/security/azure-security-disk-encryption-appendix.md)
* Service: **security**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16600](https://github.com/MicrosoftDocs/azure-docs/issues/16600) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @ithahn 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/16600.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
