### ISSUE TITLE
Old repo still on Azure org

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/azure-docs.de-de#143]
Came across https://github.com/Azure/azure-content-dede which looks like it was an old version of this repo. Maybe it should get removed to prevent confusion

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17364](https://github.com/MicrosoftDocs/azure-docs/issues/17364) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @nschonni: 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/17364

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
