### ISSUE TITLE
Where is the sample code

### ISSUE THREAD

**Issue by msched** [MicrosoftDocs/azure-docs.de-de#153]
Hey, where do I find the C#, Python and R sample code mentioned in the article?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: edc98ded-e57a-f28e-89c4-6b352476609e
* Version Independent ID: 4345a74c-afeb-d48d-0cf3-68aee6a56007
* Content: [Programmgesteuertes erneutes Trainieren von Machine Learning-Modellen](https://docs.microsoft.com/de-de/azure/machine-learning/studio/retrain-models-programmatically)
* Content Source: [articles/machine-learning/studio/retrain-models-programmatically.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/machine-learning/studio/retrain-models-programmatically.md)
* Service: **machine-learning**
* GitHub Login: @YasinMSFT
* Microsoft Alias: **yahajiza**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19986](https://github.com/MicrosoftDocs/azure-docs/issues/19986) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @msched 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/19986.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
