### ISSUE TITLE
Build your first project - step 6

### ISSUE THREAD

**Issue by DavidZID** [MicrosoftDocs/azure-docs.de-de#163]
Hi there
At step 6 of build your first project, there is a function called "IoT Workbench: Cloud", but this doesn't exists. So I wasn't able to do this tutorial. Anyway, the Extension in VSCode has a new name - please correct that as well. It would make sense to try the hole example. Thanks a lot for your support.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0cf9b53c-0438-f23c-fd2e-d57481d57e85
* Version Independent ID: f01afd66-d093-ac44-2b20-df225530b39e
* Content: [IoT DevKit in der Cloud – Verbinden von IoT DevKit AZ3166 mit Azure IoT Hub](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started#prepare-your-hardware)
* Content Source: [articles/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started.md)
* Service: **iot-hub**
* GitHub Login: @rangv
* Microsoft Alias: **rangv**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21092](https://github.com/MicrosoftDocs/azure-docs/issues/21092) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DavidZID 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/21092.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
