### ISSUE TITLE
Supported OS

### ISSUE THREAD

**Issue by dimilider** [MicrosoftDocs/azure-docs.de-de#255]
Hey all, 

the documentation is mentioning that the most used OS's are not supported -> https://docs.microsoft.com/de-de/azure/virtual-machines/extensions/dsc-linux#operating-system . btw, the link to the supported OS's is down. But on a other GitHub page (https://github.com/Microsoft/PowerShell-DSC-for-Linux#supported-linux-operating-systems) the OS's are supported. I think there is a missmatch between the both sources? 

Regards, 
Dimitri

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24003](https://github.com/MicrosoftDocs/azure-docs/issues/24003) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @dimilider 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/24003.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
