### ISSUE TITLE
GPO path to policy is wrong

### ISSUE THREAD

**Issue by DirkRinge** [MicrosoftDocs/azure-docs.de-de#259]
In the documentation above it is state that the policy can be found at: Computer Configuration &gt; Policies &gt; Administrative Templates &gt; Windows Components &gt; Workplace Join &gt; Automatically workplace join client computers.
But at least with 1809 the path is Computer Configuration &gt; Policies &gt; Administrative Templates &gt; Windows Components &gt; Device Registration &gt; Register domain joined computer as device.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2928e23e-3210-9e74-9cdb-1a19b703eac7
* Version Independent ID: 44e303ca-e4bc-ba30-5aae-311aa9318278
* Content: [Steuern von Azure AD Hybrid Join für Ihre Geräte](https://docs.microsoft.com/de-de/azure/active-directory/devices/hybrid-azuread-join-control)
* Content Source: [articles/active-directory/devices/hybrid-azuread-join-control.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory/devices/hybrid-azuread-join-control.md)
* Service: **active-directory**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25197](https://github.com/MicrosoftDocs/azure-docs/issues/25197) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DirkRinge 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25197

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
