### ISSUE TITLE
Scale set automatic OS image upgrades not considered here

### ISSUE THREAD

**Issue by DirkRinge** [MicrosoftDocs/azure-docs.de-de#262]
This document does not incorporate the VMSS automatic OS image upgrades feature that seems to change the best practices for keeping a cluster up to date on Azure.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a1cb62ea-6ede-d585-5952-24c9958c0364
* Version Independent ID: 71c4b645-51dd-391f-4b4f-d669e3487c0b
* Content: [Upgrade eines Azure Service Fabric-Clusters](https://docs.microsoft.com/de-de/azure/service-fabric/service-fabric-cluster-upgrade)
* Content Source: [articles/service-fabric/service-fabric-cluster-upgrade.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/service-fabric/service-fabric-cluster-upgrade.md)
* Service: **service-fabric**
* GitHub Login: @aljo-microsoft
* Microsoft Alias: **aljo**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #26192](https://github.com/MicrosoftDocs/azure-docs/issues/26192) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DirkRinge 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/26192

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
