### ISSUE TITLE
The host name hello_world.azurewebsites.net is invalid.

### ISSUE THREAD

**Issue by BujarMurati** [MicrosoftDocs/azure-docs.de-de#264]
Following the tutorial returns the error in the title after the command:
 az webapp up -n hello_world

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0077a811-b0b7-93b1-80b0-a4d45615ef4b
* Version Independent ID: cc95198d-5560-2bf1-09ae-b8d210e45f2d
* Content: [Erstellen von Python-Apps unter Linux: Azure App Service](https://docs.microsoft.com/de-de/azure/app-service/containers/quickstart-python#feedback)
* Content Source: [articles/app-service/containers/quickstart-python.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/app-service/containers/quickstart-python.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #26710](https://github.com/MicrosoftDocs/azure-docs/issues/26710) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @BujarMurati 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/26710

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
