### ISSUE TITLE
Wrong Example Snippet in the "Restrict caller IPs" section

### ISSUE THREAD

**Issue by WenzelS** [MicrosoftDocs/azure-docs.de-de#269]
&lt;ip-filter action="allow | forbid"&gt;  
    &lt;address&gt;address&lt;/address&gt;  
    &lt;address-range from="address" to="address" /&gt;  
&lt;/ip-filter&gt;  

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 248a0753-0fa7-1cc0-d13a-d378ab182e95
* Version Independent ID: 7efa247a-7184-6e7f-c1f5-3ff2531df357
* Content: [Azure API Management-Richtlinien für die Zugriffsbeschränkung](https://docs.microsoft.com/de-de/azure/api-management/api-management-access-restriction-policies#feedback)
* Content Source: [articles/api-management/api-management-access-restriction-policies.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/api-management/api-management-access-restriction-policies.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by CeciAc** [comment]
Hello, @WenzelS 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/28246

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
