### ISSUE TITLE
Creating Azure KeyVault key uses an invalid command.

### ISSUE THREAD

**Issue by woehrl01** [MicrosoftDocs/azure-docs.de-de#270]
The command which is used is invalid. The correct command is `Add-AzKeyVaultKey` instead of `Add-AzureKeyVaultKey`.

It's wrong in the text and the example. The link leads to the correct page though.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 86b44bac-c760-a06d-e618-149f275e0d0e
* Version Independent ID: bcaaf53e-87c1-59aa-c51b-d3359ebb9046
* Content: [Verschlüsseln von Datenträgern auf einem virtuellen Windows-Computer in Azure](https://docs.microsoft.com/de-de/azure/virtual-machines/windows/encrypt-disks#feedback)
* Content Source: [articles/virtual-machines/windows/encrypt-disks.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/virtual-machines/windows/encrypt-disks.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #28268](https://github.com/MicrosoftDocs/azure-docs/issues/28268) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @woehrl01 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/28268

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
