### ISSUE TITLE
The stub domain example returns validation errors

### ISSUE THREAD

**Issue by Lycrosa** [MicrosoftDocs/azure-docs.de-de#278]
first of all you cant apply it with the command you provided, second of all, if I apply it with kubectl apply -f coredns-custom.yaml I get a validation error

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f95537e-770a-739c-0175-4447a995f8b2
* Version Independent ID: 6c9a1132-05af-70f1-5a2b-8dad56de9cc3
* Content: [Anpassen von CoreDNS für Azure Kubernetes Service (AKS)](https://docs.microsoft.com/de-de/azure/aks/coredns-custom)
* Content Source: [articles/aks/coredns-custom.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/aks/coredns-custom.md)
* Service: **container-service**
* GitHub Login: @jnoller
* Microsoft Alias: **jnoller**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #29158](https://github.com/MicrosoftDocs/azure-docs/issues/29158) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Lycrosa 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/29158

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
