### ISSUE TITLE
Maybe it would be great to have a extra section to the license topic...

### ISSUE THREAD

**Issue by nielsophey** [MicrosoftDocs/azure-docs.de-de#279]
It might be better to find and understand if the section "Overview" would be devided in "what is..." and "requierements" including the right licensing...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d2eeca14-80ef-c0b4-2719-80ceb286ba3d
* Version Independent ID: b7d3df23-3158-2807-eecc-73e7230c2033
* Content: [Was ist Windows Virtual Desktop (Vorschauversion)?  - Azure](https://docs.microsoft.com/de-de/azure/virtual-desktop/overview#feedback)
* Content Source: [articles/virtual-desktop/overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/virtual-desktop/overview.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #29162](https://github.com/MicrosoftDocs/azure-docs/issues/29162) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @nielsophey 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/29162

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
