### ISSUE TITLE
VNET Integration outdated?

### ISSUE THREAD

**Issue by Spagoot420** [MicrosoftDocs/azure-docs.de-de#280]
I'm pretty sure this part right here is outdated:
https://docs.microsoft.com/de-de/azure/app-service/web-sites-integrate-with-vnet#configure-vnet-integration-with-your-app

First of all, the text at 1. is now called "Click here to manage"
Also the window that pops up looks nothing like what is shown in the following screenshots. Is there an updated Version of this post available?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a7a98803-1438-b1b5-f543-7dd88bc4294e
* Version Independent ID: 37ff1d0f-ed8e-5e4d-1f4c-1b9f6cffb938
* Content: [Integrieren einer App in ein Azure Virtual Network – Azure App Service](https://docs.microsoft.com/de-de/azure/app-service/web-sites-integrate-with-vnet#configure-vnet-integration-with-your-app)
* Content Source: [articles/app-service/web-sites-integrate-with-vnet.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/app-service/web-sites-integrate-with-vnet.md)
* Service: **app-service**
* GitHub Login: @ccompy
* Microsoft Alias: **ccompy**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #29225](https://github.com/MicrosoftDocs/azure-docs/issues/29225) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Spagoot420 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/29225

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
