### ISSUE TITLE
Usage of tags needs to be updated. 

### ISSUE THREAD

**Issue by sharbag** [MicrosoftDocs/azure-docs.de-de#354]
Terraform usage of "Tags" was changed in last versions from "tags { ... }" to "tags = { .... }" therefore this example is not working anymore. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 163088fc-67d3-aa81-26e7-0155f3aaa90c
* Version Independent ID: fafceb81-d8fc-8c20-72e5-b2dddc445f73
* Content: [Verwenden von Terraform zum Erstellen einer vollständigen Linux-VM in Azure](https://docs.microsoft.com/de-de/azure/virtual-machines/linux/terraform-create-complete-vm#feedback)
* Content Source: [articles/virtual-machines/linux/terraform-create-complete-vm.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-machines/linux/terraform-create-complete-vm.md)
* Service: **virtual-machines-linux**
* GitHub Login: @echuvyrov
* Microsoft Alias: **echuvyrov**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32035](https://github.com/MicrosoftDocs/azure-docs/issues/32035) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @sharbag 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32035

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
