### ISSUE TITLE
azure is removed from ansible from version 2.8 ?

### ISSUE THREAD

**Issue by cpolzer** [MicrosoftDocs/azure-docs.de-de#369]
Please note in your docs, that azure is removed from ansible from version 2.8. https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#removed-features-previously-deprecated

Maybe provide link to the new solution?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 54d793fc-86e3-ff1c-c06a-2a77df00e983
* Version Independent ID: 4c134f4c-a4a1-7675-4d10-f8e7786d46ed
* Content: [Verwenden von Ansible mit Azure](https://docs.microsoft.com/de-de/azure/ansible/ansible-overview#feedback)
* Content Source: [articles/ansible/ansible-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/ansible/ansible-overview.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32383](https://github.com/MicrosoftDocs/azure-docs/issues/32383) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @cpolzer 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by cpolzer** [comment]
Thx;)

Viele Grüße,
Christian Polzer
