### ISSUE TITLE
Simple text issue

### ISSUE THREAD

**Issue by inputoutputcode** [MicrosoftDocs/azure-docs.de-de#390]
Just a minor issue, the text section around the headline "Next steps" is duplicated and has a display issue.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 77a03366-6bf3-c687-d9e4-39eb8774d3a2
* Version Independent ID: ac420896-0070-59b1-6a76-376c3ed22875
* Content: [Netzwerkmuster für Azure Service Fabric](https://docs.microsoft.com/de-de/azure/service-fabric/service-fabric-patterns-networking)
* Content Source: [articles/service-fabric/service-fabric-patterns-networking.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/service-fabric/service-fabric-patterns-networking.md)
* Service: **service-fabric**
* GitHub Login: @aljo-microsoft
* Microsoft Alias: **aljo**

**Comment by CeciAc** [comment]
Hello, @inputoutputcode

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33030

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
