### ISSUE TITLE
Issues with tags in k8s.tf

### ISSUE THREAD

**Issue by wuerzelchen** [MicrosoftDocs/azure-docs.de-de#476]
Terraform v0.12.5
+ provider.azurerm v1.31.0
    
   tags {
        Environment = "Development"
    }

should be
    tags = {
        Environment = "Development"
    }

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c22b6ec6-7a27-4029-ff8f-674a40c0e552
* Version Independent ID: bd2884f3-831a-3761-0502-5eb1594872bd
* Content: [Erstellen eines Kubernetes-Clusters mit Azure Kubernetes Service (AKS) und Terraform](https://docs.microsoft.com/de-de/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks#feedback)
* Content Source: [articles/terraform/terraform-create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/terraform/terraform-create-k8s-cluster-with-tf-and-aks.md)
* Service: **azure**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by srvbpigh** [comment]
Hello, @wuerzelchen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35595](https://github.com/MicrosoftDocs/azure-docs/issues/35595) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @wuerzelchen

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35595

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
