### ISSUE TITLE
Windows Server 2016

### ISSUE THREAD

**Issue by AWeber78** [MicrosoftDocs/azure-docs.de-de#501]
why two lines for Windows Server 2016? Could this not merged?

**Comment by srvbpigh** [comment]
Hello, @AWeber78
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @AWeber78 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by AWeber78** [comment]
Hello,

Thanks for the question. The article changed tonight. Now it is right from my point of view.

https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/technical-reference#client-apps-condition

Kind Regards

Andreas

**Comment by CeciAc** [comment]
Hello, @AWeber78 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
