### ISSUE TITLE
Certificate information outdated

### ISSUE THREAD

**Issue by jschibberges** [MicrosoftDocs/azure-docs.de-de#535]
See this reddit-thread for information how to configure the certificate information correctly

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 685925a8-7d2b-170f-7c34-a28f5f7f0764
* Version Independent ID: bb4e6ca9-b1ce-2b11-f367-c6889a93ba0c
* Content: [Tutorial: Azure Active Directory-Integration mit FreshDesk](https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/freshdesk-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/freshdesk-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/saas-apps/freshdesk-tutorial.md)
* Service: **active-directory**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by srvbpigh** [comment]
Hello, @jschibberges
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jschibberges
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team
