### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jayonthenet** [MicrosoftDocs/azure-docs.de-de#573]
Please have a look at section 5 https://docs.microsoft.com/de-de/azure/cloudfoundry/how-cloud-foundry-integrates-with-azure#5-open-service-broker - the link to the tile on Pivotal network is broken (https://network.pivotal.io/products/azure-open-service-broker-pcf/)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6c9ac04f-e205-f3c5-8b7e-9c629cc115e2
* Version Independent ID: 4c54cb04-3ac6-7fbe-cc80-efb88da8b94f
* Content: [Integration von Cloud Foundry in Azure](https://docs.microsoft.com/de-de/azure/cloudfoundry/how-cloud-foundry-integrates-with-azure#5-open-service-broker)
* Content Source: [articles/cloudfoundry/how-cloud-foundry-integrates-with-azure.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cloudfoundry/how-cloud-foundry-integrates-with-azure.md)
* Service: **virtual-machines-linux**
* GitHub Login: @ningk
* Microsoft Alias: **ningk**

**Comment by srvbpigh** [comment]
Hello, @jayonthenet
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @jayonthenet 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/40122.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
