### ISSUE TITLE
Missing instructions via ARM or CLI

### ISSUE THREAD

**Issue by jhueppauff** [MicrosoftDocs/azure-docs.de-de#578]
Please add additional documentation on how to achieve this with ARM

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b32fbbf3-178d-a0ef-7c3a-87df74a8eb16
* Version Independent ID: 2475b34a-88e8-5b45-723d-ee0a62230b8a
* Content: [Tutorial – Hinzufügen einer benutzerdefinierten Domäne zum Azure CDN-Endpunkt](https://docs.microsoft.com/de-de/azure/cdn/cdn-map-content-to-custom-domain#feedback)
* Content Source: [articles/cdn/cdn-map-content-to-custom-domain.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cdn/cdn-map-content-to-custom-domain.md)
* Service: **azure-cdn**
* GitHub Login: @mdgattuso
* Microsoft Alias: **magattus**

**Comment by srvbpigh** [comment]
Hello, @jhueppauff
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #41250](https://github.com/MicrosoftDocs/azure-docs/issues/41250) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @jhueppauff

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41250

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
