### ISSUE TITLE
HTTPS Trigger for flow is a premium feature

### ISSUE THREAD

**Issue by boehmmic44** [MicrosoftDocs/azure-docs.de-de#579]
Unfortunately the https trigger is a pemium flow feature. So you need a user who pays 15$ every month or you buy 5 flows for 500$ only to configure the lead management for the azure marketplace listing. This is very bad.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2319bae2-e023-07fd-28e1-b0b10bf33a22
* Version Independent ID: 0a00e889-20d4-9ef4-5935-15dc67059d61
* Content: [HTTPS-Endpunkt](https://docs.microsoft.com/de-de/azure/marketplace/partner-center-portal/commercial-marketplace-lead-management-instructions-https#feedback)
* Content Source: [articles/marketplace/partner-center-portal/commercial-marketplace-lead-management-instructions-https.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/marketplace/partner-center-portal/commercial-marketplace-lead-management-instructions-https.md)
* Service: **marketplace**
* GitHub Login: @qianw211
* Microsoft Alias: **evansma**

**Comment by srvbpigh** [comment]
Hello, @boehmmic44
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @boehmmic44 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41455

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
