### ISSUE TITLE
Needed URLs+Port Whitelisting 

### ISSUE THREAD

**Issue by sawolfe91** [MicrosoftDocs/azure-docs.de-de#585]
Our Sever needed additionally the URL ne.configuration.dataproxy.clouddatahub.net:443 whitelisting for the  setup, this info is missing above :)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 32785d15-8202-6e44-f1d2-420ef0600f3f
* Version Independent ID: 3af5fa49-7bd4-18ce-f8dc-aa4a2b8c6478
* Content: [Erstellen einer selbstgehosteten Integration Runtime in Azure Data Factory](https://docs.microsoft.com/de-de/azure/data-factory/create-self-hosted-integration-runtime?source=docs#feedback)
* Content Source: [articles/data-factory/create-self-hosted-integration-runtime.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/data-factory/create-self-hosted-integration-runtime.md)
* Service: **data-factory**
* GitHub Login: @nabhishek
* Microsoft Alias: **abnarain**

**Comment by srvbpigh** [comment]
Hello, @sawolfe91
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #42122](https://github.com/MicrosoftDocs/azure-docs/issues/42122) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @sawolfe91

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/42122

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
