### ISSUE TITLE
SAP ECC 6.0 EHP 7 supported?

### ISSUE THREAD

**Issue by darealgoku** [MicrosoftDocs/azure-docs.de-de#586]
Hi, before we start to implement ETL processes based on source SAP ERP (ECC) 6.0 EHP 7. I would like to know if the Version of SAP is supported by the SAP table connector. The documentation doesn't point this out very clearly. Thanks in advanced.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6445960a-ba4e-8e08-d9a7-326d35f902b6
* Version Independent ID: fddcb50b-f74e-ce0d-af42-991587f456ca
* Content: [Kopieren von Daten aus einer SAP-Tabelle mithilfe von Azure Data Factory](https://docs.microsoft.com/de-de/azure/data-factory/connector-sap-table)
* Content Source: [articles/data-factory/connector-sap-table.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/data-factory/connector-sap-table.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by CeciAc** [comment]
Hello, @darealgoku

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/42269

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
