### ISSUE TITLE
VHD is shown als managed in Azure CLI but there is no page blob in the blob storage

### ISSUE THREAD

**Issue by jgesch** [MicrosoftDocs/azure-docs.de-de#590]
Hello,
I used the command   _az vm list -d_  in the Azure CLI.
There in the output in the parameter storageProfile.dataDisks.managedDisk are the informations about an added VHD to a VM. Does managedDisk imply that the disk is automatically managed? if so, shouldn't it be stored as a page blob? 
Because the CLI is showing me the disk but in my blob storage I counldn't find any hint of it. Theres just the log file of my VM.

Thanks in advance for the help

**Comment by srvbpigh** [comment]
Hello, @jgesch
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Issue moved to [MicrosoftDocs/azure-docs #42649](https://github.com/MicrosoftDocs/azure-docs/issues/42649) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
Hello, @jgesch ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/42649.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
