### ISSUE TITLE
nice example for payload but missing explanation

### ISSUE THREAD

**Issue by robert-bachmann** [MicrosoftDocs/azure-docs.de-de#591]
This page is good to see what a payload could look like. But it would be also good to have a list of possible values in the fields described below each example. See the example does not help to process the json content. For that I would need to know what can be the possible data in the fields.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7e4d20cc-b693-ee2d-2694-832b455376a6
* Version Independent ID: 7b929793-dba5-8f94-e44f-7dace50ee018
* Content: [Definitionen des allgemeinen Warnungsschemas für Azure Monitor](https://docs.microsoft.com/de-de/azure/azure-monitor/platform/alerts-common-schema-definitions#feedback)
* Content Source: [articles/azure-monitor/platform/alerts-common-schema-definitions.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-monitor/platform/alerts-common-schema-definitions.md)
* Service: **azure-monitor**
* Sub-service: **alerts**
* GitHub Login: @anantr
* Microsoft Alias: **robb**

**Comment by srvbpigh** [comment]
Hello, @robert-bachmann
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @robert-bachmann

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43225

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
