### ISSUE TITLE
Wrong units of network bandwidth in some virtual machine categories above

### ISSUE THREAD

**Issue by mikerobyn** [MicrosoftDocs/azure-docs.de-de#592]
Some examples how the bandwidth is decalred in some specs of virtual machine categories:
DC-Series: Mbps (e.g. DC2s 1500Mbps)
Dav4-series: MBps (e.g. D2as_v4 1000MBps)
Dv3-series: No unit declared.

I guess D2as_v5 does not support 8Gbit/s? Even if this should be correct, inconsistent declaration of units should be avoided. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9bb1d37c-6337-0906-42ff-b5dbc6afdc8b
* Version Independent ID: 72a96e16-1d2d-4c01-45be-3caf82470592
* Content: [Größen von virtuellen Azure Windows-Computern – Allgemeiner Zweck](https://docs.microsoft.com/de-de/azure/virtual-machines/windows/sizes-general#feedback)
* Content Source: [articles/virtual-machines/windows/sizes-general.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-machines/windows/sizes-general.md)
* Service: **virtual-machines-windows**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by srvbpigh** [comment]
Hello, @mikerobyn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mikerobyn

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/azure-docs/issues/43406

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
