### ISSUE TITLE
Connection opened too soon.

### ISSUE THREAD

**Issue by maryob77062** [MicrosoftDocs/azure-docs.de-de#595]
Why do I try to teach that connections should not be opened until needed when you code opens it way before the .Execute...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6f9d2f1e-c439-d629-2d03-9da4eb542cef
* Version Independent ID: d6590169-e5b0-4c75-4465-3a72ee199ce5
* Content: [Verwenden von Visual Studio mit .NET und C# zum Abfragen](https://docs.microsoft.com/de-de/azure/sql-database/sql-database-connect-query-dotnet-visual-studio)
* Content Source: [articles/sql-database/sql-database-connect-query-dotnet-visual-studio.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/sql-database/sql-database-connect-query-dotnet-visual-studio.md)
* Service: **sql-database**
* Sub-service: **development**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @maryob77062
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @maryob77062

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43751

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
