### ISSUE TITLE
It should be mentions in the docs that not all overload of StartsWith are supported

### ISSUE THREAD

**Issue by mhabibal13** [MicrosoftDocs/azure-docs.de-de#596]
It was frustrating that StartsWith throws a not supported exception, although it is already supported. We just found out this was the case when calling the overlad `public bool StartsWith(String value, StringComparison comparisonType)`.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7af26f57-f473-916a-bd4d-0918ef9eefcd
* Version Independent ID: b553182a-4d34-96d6-219e-1abbd031c642
* Content: [LINQ to SQL-Übersetzung in Azure Cosmos DB](https://docs.microsoft.com/de-de/azure/cosmos-db/sql-query-linq-to-sql)
* Content Source: [articles/cosmos-db/sql-query-linq-to-sql.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cosmos-db/sql-query-linq-to-sql.md)
* Service: **cosmos-db**
* GitHub Login: @timsander1
* Microsoft Alias: **tisande**

**Comment by srvbpigh** [comment]
Hello, @mhabibal13
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mhabibal13

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43756

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
