### ISSUE TITLE
HTTP/2 to backend server

### ISSUE THREAD

**Issue by git001** [MicrosoftDocs/azure-docs.de-de#601]
You explain here that HTTP/2 is used for the communication on the Browser (Front door) can I use also HTTP/2 to the backend server?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: dbadca96-7341-36d0-8a38-1c6a5c96b22d
* Version Independent ID: 2fad91dc-25f8-0c7a-c21d-93986ec51145
* Content: [Azure Front Door Service](https://docs.microsoft.com/de-de/azure/frontdoor/front-door-overview)
* Content Source: [articles/frontdoor/front-door-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/frontdoor/front-door-overview.md)
* Service: **frontdoor**
* GitHub Login: @sharad4u
* Microsoft Alias: **sharadag**

**Comment by srvbpigh** [comment]
Hello, @git001
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @git001

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/44232

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
