### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sn1ce** [MicrosoftDocs/azure-docs.de-de#602]
Hello!

There is a typo on this site,

resource "azurerm_public_ip" "jumpbox" {
 name                         = "jumpbox-public-ip"
 location                     = var.location
 resource_group_name          = azurerm_resource_group.vmss.name
 allocation_method = "Static"
 domain_name_label            = "${random_string.fqdn.result}-ssh"
 tags                         = var.tags} .  &lt;------------- // Needs to be removed! :-)
}

Kind regards

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 744c0642-d2d6-1db2-a208-d39777129d70
* Version Independent ID: 6cf61e7f-f58a-e738-bb3f-cc8a69ce3d24
* Content: [Tutorial: Erstellen einer Azure-VM-Skalierungsgruppe unter Verwendung von Terraform](https://docs.microsoft.com/de-de/azure/terraform/terraform-create-vm-scaleset-network-disks-hcl#feedback)
* Content Source: [articles/terraform/terraform-create-vm-scaleset-network-disks-hcl.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/terraform/terraform-create-vm-scaleset-network-disks-hcl.md)

**Comment by srvbpigh** [comment]
Hello, @sn1ce
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @sn1ce

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/44510

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
