### ISSUE TITLE
Change in variable names

### ISSUE THREAD

**Issue by vstokelbusch** [MicrosoftDocs/azure-docs.de-de#607]
Hi,
the caption of "iso6391Name" in the output JSON was changed to "iso6391_name". Same goes for the node "detectedLanguages", which is now "detected_languages". Additional node in the output is "additional_properties", but I'm not sure what it contains, since it was empty in my runs. Sadly I don`t have any information when the changes where made.

Cheers
Vincent

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f54a96e6-ea39-c972-1ee9-56c05be8279a
* Version Independent ID: ad96d498-d74e-1aaf-6740-a7f8a03ac7f9
* Content: [Sprachenerkennung mit der Textanalyse-REST-API - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-language-detection#feedback)
* Content Source: [articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-language-detection.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-language-detection.md)
* Service: **cognitive-services**
* Sub-service: **text-analytics**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @vstokelbusch
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @vstokelbusch, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
