### ISSUE TITLE
ClientCredentialFactory.create() was renamend

### ISSUE THREAD

**Issue by FelixJongleur42** [MicrosoftDocs/azure-docs.de-de#612]
Please adjust, ClientCredentialFactory.create() methods where renamed

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 08bcd9e7-d45f-1867-185a-c74636a9f448
* Version Independent ID: 20e2b7a4-12b0-8cbf-d36f-63a9b527b7da
* Content: [Konfigurieren von Daemon-Apps, die Web-APIs aufrufen: Microsoft Identity Platform](https://docs.microsoft.com/de-de/azure/active-directory/develop/scenario-daemon-app-configuration?tabs=java#feedback)
* Content Source: [articles/active-directory/develop/scenario-daemon-app-configuration.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/develop/scenario-daemon-app-configuration.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @jmprieur
* Microsoft Alias: **jmprieur**

**Comment by srvbpigh** [comment]
Hello, @FelixJongleur42
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @FelixJongleur42 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by FelixJongleur42** [comment]
Why do you close the issue when it‘s not solved? Apparently the method names of the above mentioned class where refactored and you should update the documentation to reflect this. I‘m not quite sure what more needs to be explained? Maybe you should look at the corresponding API

**Comment by srvbpigh** [comment]
Hello, @FelixJongleur42, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46317. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
