### ISSUE TITLE
Is this API working?

### ISSUE THREAD

**Issue by FredStober** [MicrosoftDocs/azure-docs.de-de#613]
I tried the powershell and python examples (after porting them to python3).
The REST API returns with status 200 - so it seems to be successful.
However in both cases I can watch how the logging table is created with the custom fields in my workspace. However the entries in that table never appear.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1295e1b3-5aed-3aee-4331-8b81e7a7e544
* Version Independent ID: 3c00a5ee-7093-1e8b-9004-8fed3f82960e
* Content: [HTTP-Datensammler-API von Azure Monitor](https://docs.microsoft.com/de-de/azure/azure-monitor/platform/data-collector-api#feedback)
* Content Source: [articles/azure-monitor/platform/data-collector-api.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-monitor/platform/data-collector-api.md)
* Service: **azure-monitor**
* Sub-service: **logs**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by srvbpigh** [comment]
Hello, @FredStober
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @FredStober, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46225. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
