### ISSUE TITLE
Using common endpoint for admin consent is wrong

### ISSUE THREAD

**Issue by barisbikmaz** [MicrosoftDocs/azure-docs.de-de#617]
The docu says in the section **Request the permissions from a directory admin**

tenant | Required | The directory tenant that you want to request permission from. Can be provided in GUID or friendly name format ""_OR generically referenced with common_"" as seen in the example.
-- | -- | --

But this is wrong. You can't use the common endpoint, just organizations.
It is also not used in the example.

**Comment by srvbpigh** [comment]
Hello, @barisbikmaz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @barisbikmaz, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47234. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47236](https://github.com/MicrosoftDocs/azure-docs/issues/47236) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ticianaciminari** [comment]
Hello, @barisbikmaz,

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47236. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
