### ISSUE TITLE
Data location Switzerland & Germany missing

### ISSUE THREAD

**Issue by Allaen** [MicrosoftDocs/azure-docs.de-de#621]
First table has missing entries for Switzerland and Germany.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b285f539-0487-0de5-24ef-89f773a1081d
* Version Independent ID: b4f26f73-6b46-9703-692b-abe1f0d5f825
* Content: [Azure AD Connect: Konfigurieren des bevorzugten Datenspeicherorts für Office 365-Ressourcen](https://docs.microsoft.com/de-de/azure/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @Allaen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47796](https://github.com/MicrosoftDocs/azure-docs/issues/47796) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Allaen, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47796. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
