### ISSUE TITLE
Group.Unified.Guest setting clarification

### ISSUE THREAD

**Issue by Allaen** [MicrosoftDocs/azure-docs.de-de#624]
It might be good to mention that the Group.Unified.Guest template only supports the "AllowToAddGuests" setting. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4cd7a703-534a-5fbd-6470-5d29bf512fd2
* Version Independent ID: 4f70ed16-6a1c-c0be-3c5e-d56e1b7c7275
* Content: [Konfigurieren von Gruppeneinstellungen mit PowerShell – Azure AD](https://docs.microsoft.com/de-de/azure/active-directory/users-groups-roles/groups-settings-cmdlets#feedback)
* Content Source: [articles/active-directory/users-groups-roles/groups-settings-cmdlets.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/users-groups-roles/groups-settings-cmdlets.md)
* Service: **active-directory**
* Sub-service: **users-groups-roles**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @Allaen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48170](https://github.com/MicrosoftDocs/azure-docs/issues/48170) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Allaen, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48170. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
