### ISSUE TITLE
Heading 5, Issuer

### ISSUE THREAD

**Issue by rpeters-gom** [MicrosoftDocs/azure-docs.de-de#626]
I think in heading 5
Issuer: https://tenant-name.onmicrosoft.com/policy-name 

should be
Issuer: https://tenant-name.b2clogin.com/tenant-name.onmicrosoft.com/policy-name 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1376f79b-474f-4b83-2583-07acd2eeb2f4
* Version Independent ID: 45d314dd-c9fa-50a5-cb39-d34db80c7874
* Content: [Konfigurieren von Azure AD B2C als SAML-IDP für Ihre Anwendungen](https://docs.microsoft.com/de-de/azure/active-directory-b2c/connect-with-saml-service-providers#feedback)
* Content Source: [articles/active-directory-b2c/connect-with-saml-service-providers.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory-b2c/connect-with-saml-service-providers.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @rpeters-gom
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48798](https://github.com/MicrosoftDocs/azure-docs/issues/48798) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @rpeters-gom, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48798. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
