### ISSUE TITLE
Release path not valid

### ISSUE THREAD

**Issue by MichaKnoe** [MicrosoftDocs/azure-docs.de-de#627]
The given release path seems to be not valid anymore:
"https://github.com/istio/istio/releases/download/$ISTIO_VERSION/istio-$ISTIO_VERSION-linux.tar.gz"

Documentation needs to be updated I guess.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6d64cf65-bf33-ff76-3ece-47c758479506
* Version Independent ID: c2db9de5-62ef-5bd0-83dc-1832113ae37c
* Content: [Installieren von Istio in Azure Kubernetes Service (AKS)](https://docs.microsoft.com/de-de/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux#feedback)
* Content Source: [articles/aks/servicemesh-istio-install.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/aks/servicemesh-istio-install.md)
* Service: **container-service**
* GitHub Login: @paulbouwer
* Microsoft Alias: **pabouwer**

**Comment by srvbpigh** [comment]
Hello, @MichaKnoe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48804](https://github.com/MicrosoftDocs/azure-docs/issues/48804) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @MichaKnoe, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48804. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
