### ISSUE TITLE
Document how private link uses redirect/proxy

### ISSUE THREAD

**Issue by ecki** [MicrosoftDocs/azure-docs.de-de#633]
If I use a Database Service with private link, will it always proxy to my database or is it using the redirect method. What's the performance implication.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b006a616-2f2f-8ecf-8b80-fd0a3cc62090
* Version Independent ID: 92c54dc6-8ddf-b1f7-4a58-d61b8cd7fe25
* Content: [Was ist privater Endpunkt in Azure?](https://docs.microsoft.com/de-de/azure/private-link/private-endpoint-overview)
* Content Source: [articles/private-link/private-endpoint-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/private-link/private-endpoint-overview.md)
* Service: **private-link**
* GitHub Login: @malopMSFT
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @ecki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50527](https://github.com/MicrosoftDocs/azure-docs/issues/50527) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @ecki, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50527. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
