### ISSUE TITLE
GET https://management.azure.com/subscriptions/089bd33f-d4ec-47fe-8ba5-0753aa5c5b33/providers/microsoft.insights/eventt

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/azure-docs.de-de#642]
GET https://management.azure.com/subscriptions/089bd33f-d4ec-47fe-8ba5-0753aa5c5b33/providers/microsoft.insights/eventt

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7ffa5b26-3e6a-38a9-8871-c8b1d3b80a94
* Version Independent ID: 63115d6a-ea00-20d4-90ed-51773c1ab896
* Content: [Anzeigen von Azure-Aktivitätsprotokollereignissen in Azure Monitor](https://docs.microsoft.com/de-de/azure/azure-monitor/platform/activity-log-view#powershell)
* Content Source: [articles/azure-monitor/platform/activity-log-view.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-monitor/platform/activity-log-view.md)
* Sub-service: **logs**
* GitHub Login: @bwren
* Microsoft Alias: **johnkem**

**Comment by srvbpigh** [comment]
Hello, @christian7877
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @christian7877 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team
