### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by claria** [MicrosoftDocs/azure-docs.de-de#645]
Timespan section:
"24:00:00" 	every 24 days
That's a typo, isn't it?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b5527c3b-a5da-c73d-66c2-20d96003ff7c
* Version Independent ID: 42154c7b-b0e0-26db-79bc-3f1673c48e40
* Content: [Trigger mit Timer für Azure Functions](https://docs.microsoft.com/de-de/azure/azure-functions/functions-bindings-timer?tabs=csharp#feedback)
* Content Source: [articles/azure-functions/functions-bindings-timer.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-functions/functions-bindings-timer.md)
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @claria
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52171](https://github.com/MicrosoftDocs/azure-docs/issues/52171) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @claria, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52171. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
