### ISSUE TITLE
Link "Dispatch an Event Grid event"

### ISSUE THREAD

**Issue by kitingChris** [MicrosoftDocs/azure-docs.de-de#648]
Link points to the current site. Please update with the correct link

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f79bffab-0af8-75fc-f800-73eb979611ad
* Version Independent ID: ca382131-4030-d1ba-44d4-35309bb91f94
* Content: [Azure Event Grid-Trigger für Azure Functions](https://docs.microsoft.com/de-de/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=csharp)
* Content Source: [articles/azure-functions/functions-bindings-event-grid-trigger.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-functions/functions-bindings-event-grid-trigger.md)
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @kitingChris
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52395](https://github.com/MicrosoftDocs/azure-docs/issues/52395) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @kitingChris, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs.de-de/issues/648. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
