### ISSUE TITLE
Limit of Enviroment Variables

### ISSUE THREAD

**Issue by Voteax** [MicrosoftDocs/azure-docs.de-de#657]
I get an 'InternalServerError' if I pass more than 15 Enviroment Variables into the DeploymentScript.
Is this a known limitation?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b5c4c8c5-7757-a969-5800-17f2f2312649
* Version Independent ID: 9ced8dd5-43ca-6d1f-c054-842299db8327
* Content: [Verwenden von Bereitstellungsskripts in Vorlagen](https://docs.microsoft.com/de-de/azure/azure-resource-manager/templates/deployment-script-template?tabs=CLI#debug-deployment-scripts)
* Content Source: [articles/azure-resource-manager/templates/deployment-script-template.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-resource-manager/templates/deployment-script-template.md)
* Service: **azure-resource-manager**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by srvbpigh** [comment]
Hello, @Voteax
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54892](https://github.com/MicrosoftDocs/azure-docs/issues/54892) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Voteax, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54892. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
