### ISSUE TITLE
Change default error message in prevention mode from 403 to 404

### ISSUE THREAD

**Issue by MaxiPalle** [MicrosoftDocs/azure-docs.de-de#659]
Is it possible to adjust the default behaviour in 'prevention' mode?
We would like to answer the AppGw with a 404 instead of 403 to make any further attack attempts less likely.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a2438dcd-deba-74d9-9552-4e6b91f61416
* Version Independent ID: da5bf632-8655-5fd1-bccb-0209cd28d34c
* Content: [Häufig gestellte Fragen zu Azure Web Application Firewall in Application Gateway](https://docs.microsoft.com/de-de/azure/web-application-firewall/ag/application-gateway-waf-faq)
* Content Source: [articles/web-application-firewall/ag/application-gateway-waf-faq.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/web-application-firewall/ag/application-gateway-waf-faq.md)
* Service: **web-application-firewall**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by srvbpigh** [comment]
Hello, @MaxiPalle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55095](https://github.com/MicrosoftDocs/azure-docs/issues/55095) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @MaxiPalle, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55095. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
