### ISSUE TITLE
priatednszonename

### ISSUE THREAD

**Issue by trehberg** [MicrosoftDocs/azure-docs.de-de#664]
"priatednszonename" should probably be "pri**v**atednszonename" ?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a7b1b215-0434-145b-cd11-95d0f32bc015
* Version Independent ID: d328a868-a151-1985-2b62-f3884f7ad76c
* Content: [Namensauflösung für Ressourcen in virtuellen Azure-Netzwerken](https://docs.microsoft.com/de-de/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances)
* Content Source: [articles/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances.md)
* Service: **virtual-network**
* GitHub Login: @rohinkoul
* Microsoft Alias: **rohink**

**Comment by srvbpigh** [comment]
Hello, @trehberg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @trehberg, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55816. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
