### ISSUE TITLE
Why should I add data disks to a virtual machine scale set?

### ISSUE THREAD

**Issue by matlion** [MicrosoftDocs/azure-docs.de-de#690]
I don't understand, why I should add manually data disks to a virtual machine scale set.
In my understanding I create PVCs via the kubernetes api which will then allocate the data disks (volumes).

Furthermore when I try to add a data disk in the virtual machine scale set this collides with the PVC allocated volumes:

`Failed to update virtual machine scale set 'aks-agentpool-24805371-vmss'. Error: LUN Collision: Disk kubernetes-dynamic-pvc-4f4ed7d9-6572-4814-8f98-0d23faaec555 is already attached at LUN 0 to VM Instance aks-agentpool-24805371-vmss_0`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 572ce9c7-8ca7-a7c3-2b76-0883025cbb5c
* Version Independent ID: 96ee5f8c-0a94-3ce4-0ce9-cdec7f48cba0
* Content: [Tutorial: Erstellen und Verwenden von Datenträgern für Skalierungsgruppen mit der Azure CLI - Azure Virtual Machine Scale Sets](https://docs.microsoft.com/de-de/azure/virtual-machine-scale-sets/tutorial-use-disks-cli)
* Content Source: [articles/virtual-machine-scale-sets/tutorial-use-disks-cli.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-machine-scale-sets/tutorial-use-disks-cli.md)
* Service: **virtual-machine-scale-sets**
* Sub-service: **disks**
* GitHub Login: @ju-shim
* Microsoft Alias: **jushiman**

**Comment by ju-shim** [comment]
Hello @matlion - 

It looks like you are running AKS (Kubernetes) and should be looking at the AKS storage documentation instead of Virtual Machine Scale Sets documentation. Here is the doc that will likely help you:

https://docs.microsoft.com/en-us/azure/aks/concepts-storage

If that does not help you, let me know and I can locate an AKS documentation contact to further assist you.

Thank you,

Julia
