### ISSUE TITLE
Looking for information about the last penetration test of Azure DevOps

### ISSUE THREAD

**Issue by RobinZergiebel** [MicrosoftDocs/azure-docs.de-de#710]
Hey,

we need Information (specifically the date) about the last penetration test (red teaming) of Azure DevOps since our security guy requests it. Could you please share?

Cheers,
Robin

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 19cb71ec-6372-f406-8542-8058f59c7ec1
* Version Independent ID: a3c05dfb-8f20-b364-526b-143f87582a18
* Content: [Penetrationstests](https://docs.microsoft.com/de-de/azure/security/fundamentals/pen-testing)
* Content Source: [articles/security/fundamentals/pen-testing.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/security/fundamentals/pen-testing.md)
* Service: **security**
* Sub-service: **security-fundamentals**
* GitHub Login: @TerryLanfear
* Microsoft Alias: **terrylan**

**Comment by RobinZergiebel** [comment]
Could someone please take a look at this issue? I don't think it requires much effort to share the date.

**Comment by TerryLanfear** [comment]
@RobinZergiebel - Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question: Microsoft Security Response Center via email to secure@microsoft.com. Because this issue does not relate to documentation, we are closing this issue.

#please-close

**Comment by RobinZergiebel** [comment]
Hey @TerryLanfear,

thank you, will do!

Cheers,
Robin
