### ISSUE TITLE
Link "Azure Data Lake Store Python (Account management) Reference" existiert nicht mehr

### ISSUE THREAD

**Issue by sauercrowd** [MicrosoftDocs/azure-docs.de-de#81]
Der Link Azure Data Lake Store Python (Account management) Reference (http://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-mgmt-datalake-store.html) ist nicht mehr erreichbar

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37375b35-1afa-f96e-793a-7fae7fb866f9
* Version Independent ID: a30f676e-b59f-b99d-03f7-4372cad84711
* Content: [Python: Kontoverwaltungsvorgänge in Azure Data Lake Store](https://docs.microsoft.com/de-de/azure/data-lake-store/data-lake-store-get-started-python)
* Content Source: [articles/data-lake-store/data-lake-store-get-started-python.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/data-lake-store/data-lake-store-get-started-python.md)
* Service: **data-lake-store**
* GitHub Login: @nitinme
* Microsoft Alias: **nitinme**

**Comment by gosali** [comment]
Hello, @sauercrowd , 

 Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by gosali** [comment]
Issue moved to [MicrosoftDocs/azure-docs #9755](https://github.com/MicrosoftDocs/azure-docs/issues/9755) via [**ZenHub**](https://www.zenhub.com/)
