### ISSUE TITLE
Problem with running telcodatagen.exe due to format error

### ISSUE THREAD

**Issue by NilsFlaschel** [MicrosoftDocs/azure-docs.de-de#82]
The command 'telcodatagen.exe 1000 .2 2' doesn't work for me. Instead 'telcodatagen.exe 1000 0.2 1' does work!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a08f205e-f19b-50e4-657d-4e97bf0121c1
* Version Independent ID: 0547fcda-7866-6001-306f-908776fb8017
* Content: [Betrugserkennung in Echtzeit mit Azure Stream Analytics](https://docs.microsoft.com/de-de/azure/stream-analytics/stream-analytics-real-time-fraud-detection#feedback)
* Content Source: [articles/stream-analytics/stream-analytics-real-time-fraud-detection.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/stream-analytics/stream-analytics-real-time-fraud-detection.md)
* Service: **stream-analytics**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #9815](https://github.com/MicrosoftDocs/azure-docs/issues/9815) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @NilsFlaschel,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/MicrosoftDocs/azure-docs/issues/9815.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
