### ISSUE TITLE
Aggregate Pipeline: sample doesn't seem to work

### ISSUE THREAD

**Issue by Lhdang88** [MicrosoftDocs/azure-docs.de-de#86]
##### expected Behavior:

collection('a').aggregate([{ $group: {...} },  {$sample: {size: 1}}])
- returns 1 random document, from group-stage (results size is &gt; 1)

##### Behavior:
- returns the first/ not random document

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a2ce2348-ba9d-8af5-7379-50aa7557379d
* Version Independent ID: 71513a03-96c9-98da-a97b-59de20ecb335
* Content: [Azure Cosmos DB-Featureunterstützung für MongoDB](https://docs.microsoft.com/de-de/azure/cosmos-db/mongodb-feature-support)
* Content Source: [articles/cosmos-db/mongodb-feature-support.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/cosmos-db/mongodb-feature-support.md)
* Service: **cosmos-db**
* GitHub Login: @alekseys
* Microsoft Alias: **alekseys**

**Comment by v-maudel** [comment]
Hello, @Lhdang88 ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10382](https://github.com/MicrosoftDocs/azure-docs/issues/10382) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Lhdang88

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/10382

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
